#!/usr/bin/env python3
"""Reflexive audit: compare the platform's self-adjudication against the suite.

The platform adjudicates OIDC OP behaviour through its own regression tests,
recorded as MUST requirements in docs/compliance/oidc-op-musts.json with a
status of verified or pending. The OIDF conformance suite is the external
reference. This script cross-checks the two and surfaces divergences:

  overclaim  platform says verified, the mapped suite module FAILED
  underclaim platform says pending, the mapped suite module PASSED

Overclaims are the dangerous case for a conformance authority: the platform's
own engine believes a rule holds while the reference disagrees. They fail CI.
Underclaims are stale-status signals and are reported as warnings. Both are
written as tracked findings to the divergence report.

Standard library only.
"""

import argparse
import glob
import json
import os
import sys

PASS_RESULTS = {"PASSED", "WARNING", "REVIEW"}
FAIL_RESULTS = {"FAILED", "TIMEOUT", "ERROR", "INTERRUPTED"}


def load_json(path):
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def collect_module_results(results_dir):
    """Map suite module name to its best-known result across all summaries."""
    module_results = {}
    for summary_path in glob.glob(os.path.join(results_dir, "**", "summary.*.json"), recursive=True):
        summary = load_json(summary_path)
        for entry in summary.get("results", []):
            module = entry.get("module")
            result = entry.get("result") or entry.get("status")
            if not module:
                continue
            # A FAILED result anywhere dominates a PASSED elsewhere.
            existing = module_results.get(module)
            if existing in FAIL_RESULTS:
                continue
            module_results[module] = result
    return module_results


def evaluate(musts, module_results):
    overclaims = []
    underclaims = []
    unobserved = []
    for req in musts.get("requirements", []):
        status = req.get("status")
        modules = req.get("suite_modules", [])
        observed = {m: module_results[m] for m in modules if m in module_results}
        if not observed:
            unobserved.append({"id": req["id"], "modules": modules})
            continue
        any_fail = any(r in FAIL_RESULTS for r in observed.values())
        all_pass = all(r in PASS_RESULTS for r in observed.values())
        if status == "verified" and any_fail:
            overclaims.append({
                "id": req["id"],
                "spec_reference": req.get("spec_reference"),
                "observed": observed,
            })
        elif status == "pending" and all_pass:
            underclaims.append({
                "id": req["id"],
                "spec_reference": req.get("spec_reference"),
                "observed": observed,
            })
    return overclaims, underclaims, unobserved


def write_report(path, overclaims, underclaims, unobserved):
    lines = ["# Adjudicator versus OIDF suite divergences", ""]
    lines.append("Generated by scripts/conformance/divergence.py. This is a tracked")
    lines.append("finding set comparing the platform self-adjudication in")
    lines.append("docs/compliance/oidc-op-musts.json against real OIDF suite results.")
    lines.append("")
    if not overclaims and not underclaims:
        lines.append("No divergences observed for the modules that ran.")
    if overclaims:
        lines.append("## Overclaims (platform verified, suite failed) - must fix")
        lines.append("")
        for item in overclaims:
            lines.append(f"- `{item['id']}` ({item['spec_reference']}): {item['observed']}")
        lines.append("")
    if underclaims:
        lines.append("## Underclaims (platform pending, suite passed) - review status")
        lines.append("")
        for item in underclaims:
            lines.append(f"- `{item['id']}` ({item['spec_reference']}): {item['observed']}")
        lines.append("")
    if unobserved:
        lines.append("## Requirements with no observed suite module this run")
        lines.append("")
        for item in unobserved:
            lines.append(f"- `{item['id']}`: {item['modules']}")
        lines.append("")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")


def main():
    parser = argparse.ArgumentParser(description="Compare adjudicator versus OIDF suite.")
    parser.add_argument("--musts", default="docs/compliance/oidc-op-musts.json")
    parser.add_argument("--results-dir", default=".artifacts/conformance")
    parser.add_argument("--report", default="docs/certification/DIVERGENCES.md")
    parser.add_argument("--fail-on-underclaim", action="store_true")
    args = parser.parse_args()

    musts = load_json(args.musts)
    module_results = collect_module_results(args.results_dir)
    overclaims, underclaims, unobserved = evaluate(musts, module_results)
    write_report(args.report, overclaims, underclaims, unobserved)

    for item in overclaims:
        print(f"::error::adjudicator overclaim {item['id']}: suite reported {item['observed']}")
    for item in underclaims:
        print(f"::warning::adjudicator underclaim {item['id']}: suite passed {item['observed']}")

    if overclaims:
        return 1
    if underclaims and args.fail_on_underclaim:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
